apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {NAMESPACE}
  name: django-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-container
        image: hub.osso.io/public/django-websocket-redis:latest
        ports:
        - containerPort: 8080
        env:
        - name: WS4REDIS_HOST
          value: "redis-service"

---

apiVersion: v1
kind: Service
metadata:
  namespace: {NAMESPACE}
  name: django-service
spec:
  ports:
    - port: 8080
  selector:
    app: django-app

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  namespace: {NAMESPACE}
  name: django-ingress
spec: 
  tls:
  - hosts:
    -  {NAMESPACE}.osso.ninja
    secretName: {NAMESPACE}-nginx-tls
  rules:
  - host: {NAMESPACE}.osso.ninja
    http:
      paths:
      - path: /
        backend:
          serviceName: django-service
          servicePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {NAMESPACE}
  name: redis-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis-container
        image: redis
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  namespace: {NAMESPACE}
  name: redis-service
spec:
  ports:
    - port: 6379
  selector:
    app: redis-app
